### ISSUE TITLE
Design ready for fabrication?

### ISSUE THREAD

**Issue by KeLaiFu** [EchelonForce/vca_as3360#1]
I have a bunch of 3360 chips that are looking for a home, is this module ready for production or still in development?

**Comment by KeLaiFu** [comment]
doh, just noticed there's a full write-up of the module on your website so the answer is obviously yes! I plan to make a 4HP version, which I will of course share on GitHub once it's finished. Thanks for your hard work!

**Comment by EchelonForce** [comment]
No worries, I'm glad it will be useful. I will double check my notes and update the repo and/or website if there's anything missing from my testing. I haven't made very many of these yet so there may be bugs still.
